[package]
name = "giphy"
version = "0.0.1"
authors = ["Maciej Makowski <maciejm.github(at)cfiet.net>"]
edition = "2018"

[dependencies]
reqwest = "0.9.9"
iso639-1 = "0.3.0"
dotenv = "0.13.0"
serde_derive = "*"
serde = "*"
# dotenv_codegen = "0.11.0"

[dev-dependencies]
mockito = "0.16.0"
